(function(){
'use strict';
var GROUPS=[
  {id:'journal',label:'Journal',icon:'◫',defaultTab:'dispatch',tabs:[['dispatch','Service Journal']]},
  {id:'calculator',label:'Calculator',icon:'⌁',defaultTab:'__calculator',tabs:[['__calculator','Projects'],['reference','Code Reference']]},
  {id:'job',label:'Job',icon:'▣',defaultTab:'quote',tabs:[['quote','Proposal'],['tm','Invoice'],['summary','Summary'],['cos','Change Orders'],['pnl','Profit & Loss']]},
  {id:'catalog',label:'Catalog',icon:'≡',defaultTab:'catalog',tabs:[['catalog','Materials Catalog'],['materials','Job Materials'],['labor','Labor & Equip'],['margins','Margins']]},
  {id:'more',label:'More',icon:'•••',defaultTab:'help',tabs:[]}
];
var currentGroup='journal',shell=null,subnav=null,bottom=null,sourceNav=null,resizeObserver=null;
var calculatorPanel=null,calculatorFrame=null,calculatorActive=false,frameResizeObserver=null,resultRail=null,resultMirror=null,resultMutationObserver=null,moreDrawer=null;
var lastByGroup={journal:'dispatch',calculator:'__calculator',job:'quote',catalog:'catalog',more:'help'};
var PROJECT_KEY='bruno-ac-project-context-v1';
function esc(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
function getGroup(id){return GROUPS.filter(function(x){return x.id===id})[0]||GROUPS[0]}
function findGroupByTab(tab){for(var i=0;i<GROUPS.length;i++)for(var j=0;j<GROUPS[i].tabs.length;j++)if(GROUPS[i].tabs[j][0]===tab)return GROUPS[i];if(tab==='personnel'||tab==='profiles'||tab==='help')return getGroup('more');return GROUPS[0]}
function sourceActiveTab(){var b=sourceNav&&sourceNav.querySelector('.nav-tab.active');return b?b.getAttribute('data-tab'):'dispatch'}
function activeTab(){return calculatorActive?'__calculator':sourceActiveTab()}
function loadProjectType(){try{var x=JSON.parse(localStorage.getItem(PROJECT_KEY)||'{}');return x.type==='commercial'?'commercial':'residential'}catch(e){return 'residential'}}
function saveProjectType(v){var type=v==='commercial'?'commercial':'residential';try{localStorage.setItem(PROJECT_KEY,JSON.stringify({type:type,updatedAt:new Date().toISOString()}))}catch(e){}return type}
function ensureCalculatorPanel(){
  if(calculatorPanel)return calculatorPanel;var main=document.querySelector('main');if(!main)return null;
  calculatorPanel=document.createElement('section');calculatorPanel.id='panel-calculator';calculatorPanel.className='panel phase3-calculator-panel';calculatorPanel.setAttribute('aria-label','Project Calculator');
  calculatorPanel.innerHTML='<div class="phase3-calculator-head"><div><h2>Project Calculator</h2><p>Code-aware scope and BOM. Select project class before calculation.</p></div><div class="phase3-project-actions"><label class="phase3-project-type">Project <select id="phase3-project-type"><option value="residential">Residential</option><option value="commercial">Commercial</option></select></label><button type="button" class="btn btn-sm" id="phase3-open-standalone">Open standalone</button></div></div><div class="phase3-project-warning" id="phase3-project-warning"></div><div class="phase4-result-rail"><aside class="phase4-result-mirror" aria-label="Calculation result"></aside></div><iframe class="phase3-calculator-frame" title="Bruno AC Code and BOM Calculator" src="./ac-calculator.html"></iframe>';
  main.appendChild(calculatorPanel);calculatorFrame=calculatorPanel.querySelector('iframe');resultRail=calculatorPanel.querySelector('.phase4-result-rail');resultMirror=calculatorPanel.querySelector('.phase4-result-mirror');
  var sel=calculatorPanel.querySelector('#phase3-project-type');sel.value=loadProjectType();syncProjectWarning();sel.addEventListener('change',function(){saveProjectType(sel.value);syncProjectWarning();if(calculatorFrame&&calculatorFrame.dataset.loaded==='1')calculatorFrame.contentWindow.location.reload()});
  calculatorPanel.querySelector('#phase3-open-standalone').addEventListener('click',function(){window.location.href='./ac-calculator.html'});
  calculatorFrame.addEventListener('load',function(){calculatorFrame.dataset.loaded='1';prepareEmbeddedCalculator()});return calculatorPanel;
}
function syncProjectWarning(){if(!calculatorPanel)return;var type=loadProjectType(),w=calculatorPanel.querySelector('#phase3-project-warning');if(!w)return;if(type==='commercial'){w.style.display='block';w.textContent='Commercial mode: residential IRC references are not treated as commercial compliance authority. Verify adopted IMC/UMC/IFGC, energy/fire requirements, local AHJ and OEM instructions.'}else{w.style.display='none';w.textContent=''}}
function syncCalculatorWideClass(){if(!calculatorFrame)return;try{var doc=calculatorFrame.contentDocument;if(doc&&doc.documentElement)doc.documentElement.classList.toggle('bruno-wide-calculator',window.innerWidth>=1180)}catch(e){}}
function fitCalculatorFrame(){if(!calculatorFrame)return;try{var doc=calculatorFrame.contentDocument;if(!doc)return;var wrap=doc.querySelector('.wrap');if(!wrap)return;var next=Math.max(760,Math.ceil(wrap.getBoundingClientRect().height+wrap.offsetTop+16)),cur=Math.round(calculatorFrame.getBoundingClientRect().height);if(Math.abs(cur-next)>1)calculatorFrame.style.height=next+'px'}catch(e){}}
function syncResultMirror(){if(!calculatorPanel||!calculatorFrame||!resultRail||!resultMirror)return;if(!calculatorActive||window.innerWidth<1180){resultRail.classList.remove('show');return}try{var doc=calculatorFrame.contentDocument,source=doc&&doc.getElementById('calcExplain'),input=doc&&doc.querySelector('.grid>.card:first-child');if(!source||!input){resultRail.classList.remove('show');return}resultMirror.innerHTML=source.innerHTML;resultMirror.className='phase4-result-mirror'+(source.classList.contains('stale-result')?' stale-result':'');var sr=source.getBoundingClientRect(),ir=input.getBoundingClientRect();resultRail.style.top=Math.round(calculatorFrame.offsetTop+sr.top)+'px';resultRail.style.left=Math.round(calculatorFrame.offsetLeft+sr.left)+'px';resultRail.style.width=Math.round(sr.width)+'px';resultRail.style.height=Math.round(Math.max(sr.height,ir.bottom-sr.top))+'px';resultRail.classList.add('show')}catch(e){resultRail.classList.remove('show')}}
function bindResultMirrorSource(){if(resultMutationObserver)try{resultMutationObserver.disconnect()}catch(e){};if(!calculatorFrame)return;try{var doc=calculatorFrame.contentDocument,source=doc&&doc.getElementById('calcExplain');if(source&&window.MutationObserver){resultMutationObserver=new MutationObserver(function(){requestAnimationFrame(function(){syncResultMirror();fitCalculatorFrame()})});resultMutationObserver.observe(source,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['class']})}}catch(e){}}
function prepareEmbeddedCalculator(){if(!calculatorFrame)return;try{var doc=calculatorFrame.contentDocument;if(!doc)return;doc.documentElement.classList.add('bruno-embedded-calculator');syncCalculatorWideClass();var old=doc.getElementById('bruno-phase3-embed-style');if(old)old.remove();var style=doc.createElement('style');style.id='bruno-phase3-embed-style';style.textContent='.bruno-embedded-calculator .top,.bruno-embedded-calculator .foot{display:none!important}.bruno-embedded-calculator body{background:transparent!important}.bruno-embedded-calculator .wrap{max-width:none!important;padding:0 4px 16px!important}.bruno-embedded-calculator .notice{margin-top:0}.bruno-embedded-calculator .grid{gap:12px}.bruno-embedded-calculator .card{box-shadow:none}.bruno-wide-calculator .grid{grid-template-columns:minmax(400px,.86fr) minmax(520px,1.14fr);align-items:start}.bruno-wide-calculator .grid>.card:nth-child(n+3){grid-column:1/-1}.bruno-wide-calculator #calcExplain{visibility:hidden}';doc.head.appendChild(style);bindResultMirrorSource();fitCalculatorFrame();syncResultMirror();setTimeout(function(){fitCalculatorFrame();syncResultMirror()},150);if(frameResizeObserver)try{frameResizeObserver.disconnect()}catch(e2){}if('ResizeObserver' in window){frameResizeObserver=new ResizeObserver(function(){requestAnimationFrame(function(){fitCalculatorFrame();syncResultMirror()})});frameResizeObserver.observe(doc.querySelector('.wrap')||doc.documentElement)}}catch(e){}}
function showCalculatorPanel(){closeMore();var existed=!!calculatorPanel,p=ensureCalculatorPanel();if(!p)return;calculatorActive=true;currentGroup='calculator';lastByGroup.calculator='__calculator';document.querySelectorAll('.panel').forEach(function(x){x.classList.remove('active')});p.classList.add('active');renderGroups();renderBottom();renderSubnav(getGroup('calculator'));scheduleMeasure();if(existed&&calculatorFrame&&calculatorFrame.dataset.loaded==='1')try{calculatorFrame.contentWindow.location.reload()}catch(e){}else requestAnimationFrame(syncResultMirror)}
function hideCalculatorPanel(){calculatorActive=false;if(calculatorPanel)calculatorPanel.classList.remove('active');if(resultRail)resultRail.classList.remove('show')}
function openTab(tab){closeMore();if(tab==='__calculator'){showCalculatorPanel();return}hideCalculatorPanel();var b=sourceNav&&sourceNav.querySelector('.nav-tab[data-tab="'+tab+'"]');if(b){b.click();setTimeout(syncFromSource,0)}}
function ensureMore(){if(moreDrawer)return moreDrawer;moreDrawer=document.createElement('div');moreDrawer.className='phase2-more-drawer no-print';moreDrawer.innerHTML='<div class="phase2-more-backdrop" data-more-close></div><div class="phase2-more-sheet"><div class="phase2-more-head"><strong>More</strong><button class="btn btn-sm" data-more-close>×</button></div><div class="phase2-more-tree"><section><h4>People & Company</h4><button data-more-tab="personnel">Workers</button><button data-more-tab="profiles">Company</button></section><section><h4>Reference & Support</h4><button data-more-tab="reference">Code Reference</button><button data-more-tab="help">Help</button></section></div></div>';document.body.appendChild(moreDrawer);moreDrawer.addEventListener('click',function(e){var t=e.target.closest('[data-more-tab]');if(t){openTab(t.getAttribute('data-more-tab'));return}if(e.target.closest('[data-more-close]'))closeMore()});return moreDrawer}
function openMore(){currentGroup='more';renderGroups();renderBottom();var d=ensureMore();d.classList.add('open')}
function closeMore(){if(moreDrawer)moreDrawer.classList.remove('open')}
function setGroup(id,openPreferred){if(id==='more'){openMore();return}closeMore();var g=getGroup(id);currentGroup=g.id;renderGroups();renderBottom();renderSubnav(g);if(openPreferred)openTab(lastByGroup[g.id]||g.defaultTab)}
function renderGroups(){var host=shell.querySelector('.phase2-groups');host.innerHTML=GROUPS.map(function(g){var active=g.id===currentGroup;return '<button type="button" class="phase2-group-btn'+(active?' active':'')+'" data-group="'+esc(g.id)+'">'+esc(g.label)+'</button>'}).join('')+'<span class="phase2-context" id="phase2-context"></span>'}
function renderBottom(){bottom.innerHTML=GROUPS.map(function(g){var active=g.id===currentGroup;return '<button type="button" class="phase2-bottom-btn'+(active?' active':'')+'" data-group="'+esc(g.id)+'"><span class="ico">'+esc(g.icon)+'</span><span>'+esc(g.label)+'</span></button>'}).join('')}
function renderSubnav(g){var tab=activeTab();subnav.innerHTML=(g.tabs||[]).map(function(t){return '<button type="button" class="phase2-sub-btn'+(t[0]===tab?' active':'')+'" data-tab="'+esc(t[0])+'">'+esc(t[1])+'</button>'}).join('');var ctx=document.getElementById('phase2-context');if(ctx){var m=(g.tabs||[]).filter(function(t){return t[0]===tab})[0];ctx.textContent=g.label+(m?' · '+m[1]:'')}scheduleMeasure()}
function syncFromSource(){calculatorActive=false;if(resultRail)resultRail.classList.remove('show');var tab=sourceActiveTab(),g=findGroupByTab(tab);currentGroup=g.id;lastByGroup[g.id]=tab;renderGroups();renderBottom();renderSubnav(g)}
function syncNavHeight(){if(!shell)return;document.documentElement.style.setProperty('--phase2-nav-h',(window.innerWidth>=768?Math.round(shell.getBoundingClientRect().height):0)+'px')}
function scheduleMeasure(){requestAnimationFrame(syncNavHeight);setTimeout(syncNavHeight,80);setTimeout(syncNavHeight,360)}
function bind(){shell.addEventListener('click',function(e){var g=e.target.closest('[data-group]');if(g){setGroup(g.getAttribute('data-group'),true);return}var t=e.target.closest('[data-tab]');if(t)openTab(t.getAttribute('data-tab'))});bottom.addEventListener('click',function(e){var g=e.target.closest('[data-group]');if(g)setGroup(g.getAttribute('data-group'),true)});if(sourceNav)new MutationObserver(function(ms){for(var i=0;i<ms.length;i++)if(ms[i].type==='attributes'){syncFromSource();break}}).observe(sourceNav,{subtree:true,attributes:true,attributeFilter:['class']});window.addEventListener('resize',function(){requestAnimationFrame(function(){syncNavHeight();syncCalculatorWideClass();fitCalculatorFrame();syncResultMirror()})});if('ResizeObserver' in window){resizeObserver=new ResizeObserver(function(){requestAnimationFrame(syncNavHeight)});resizeObserver.observe(shell)}document.addEventListener('keydown',function(e){if(e.key==='Escape')closeMore()})}
function init(){sourceNav=document.getElementById('nav-tabs');if(!sourceNav)return;sourceNav.classList.add('phase2-source-nav');shell=document.createElement('nav');shell.className='phase2-nav-shell no-print';shell.innerHTML='<div class="phase2-groups"></div><div class="phase2-subnav"></div>';sourceNav.parentNode.insertBefore(shell,sourceNav.nextSibling);subnav=shell.querySelector('.phase2-subnav');bottom=document.createElement('nav');bottom.className='phase2-bottom-nav no-print';document.body.appendChild(bottom);var dispatch=sourceNav.querySelector('.nav-tab[data-tab="dispatch"]');if(dispatch)dispatch.click();currentGroup='journal';renderGroups();renderBottom();renderSubnav(getGroup('journal'));bind();document.body.classList.add('phase2-nav-ready');document.documentElement.classList.add('phase2-nav-ready');scheduleMeasure();var after='';try{after=sessionStorage.getItem('bruno-phase3-after-apply')||'';sessionStorage.removeItem('bruno-phase3-after-apply')}catch(e){}if(after)setTimeout(function(){openTab(after)},0)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();