(function(){
'use strict';
var BUILD='bruno-ac-building-envelope-v1',LOAD='bruno-ac-load-inputs-v1';
function $(id){return document.getElementById(id)}
function esc(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function read(k,d){try{var v=JSON.parse(localStorage.getItem(k)||'null');return v&&typeof v==='object'?v:d}catch(e){return d}}
function write(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch(e){return false}}
function num(id){var e=$(id);if(!e||e.value==='')return null;var n=Number(e.value);return Number.isFinite(n)?n:null}
function fmt(v){return v==null?'—':Math.round(v).toLocaleString('en-US')}
function defaults(){return {wallExposedAreaFt2:null,roofAreaFt2:null,outdoorIndoorGrainsDifference:null,solarIrradianceBtuhFt2:null,floorCoolingDeltaF:null,floorHeatingDeltaF:null,supplyAirDeltaF:null}}
function addStyle(){if($('load-engine-style'))return;var s=document.createElement('style');s.id='load-engine-style';s.textContent=''
 +'.pls{margin:10px 0;border:1px solid #385679;border-radius:12px;background:#111a25;padding:10px}.pls h3{margin:0 0 8px}.pls-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.pls-input label{display:block;font-size:10px;color:#8fa0b6;margin-bottom:3px}.pls-input input{width:100%;min-height:40px}.pls-results{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:7px;margin-top:10px}.pls-card{border:1px solid #2d3b4d;border-radius:9px;background:#0f1720;padding:8px}.pls-card small{display:block;color:#8fa0b6}.pls-card strong{font-size:15px}.pls-state{margin-top:8px;font-size:11px}.pls-state.ok{color:#9ae6bf}.pls-state.warn{color:#ffe08a}.pls-state.bad{color:#ffb0b8}.pls-zones{margin-top:8px;font-size:11px;color:#9fb0c2}.pls-note{font-size:10px;color:#8fa0b6;margin-top:7px}@media(max-width:760px){.pls-grid{grid-template-columns:1fr 1fr}.pls-results{grid-template-columns:1fr 1fr}.pls-results .pls-card:first-child{grid-column:1/-1}}@media(max-width:430px){.pls-grid,.pls-results{grid-template-columns:1fr}.pls-results .pls-card:first-child{grid-column:auto}}';document.head.appendChild(s)}
function f(id,label,v){return '<div class="pls-input"><label>'+esc(label)+'</label><input id="'+id+'" type="number" step="any" min="0" value="'+esc(v==null?'':v)+'"></div>'}
function ensure(){var host=$('projectEstimatorWizard');if(!host||!window.BrunoLoadEngine||$('pls-load'))return false;addStyle();var s=document.createElement('section');s.id='pls-load';s.className='pls';var x=Object.assign(defaults(),read(LOAD,{}));s.innerHTML='<h3>Heating / Cooling Load</h3><div class="pls-note">Transparent envelope/load model. It is not labeled Manual J or Manual N. Missing engineering inputs block or mark the result provisional instead of inventing exact capacity.</div><div class="pls-grid">'+f('pls-wall-area','Exposed wall area (ft²)',x.wallExposedAreaFt2)+f('pls-roof-area','Roof/ceiling area (ft²)',x.roofAreaFt2)+f('pls-grains','Outdoor-indoor moisture difference (grains/lb)',x.outdoorIndoorGrainsDifference)+f('pls-solar','Solar irradiance at windows (BTU/h·ft²)',x.solarIrradianceBtuhFt2)+f('pls-floor-cool','Floor cooling ΔT (°F)',x.floorCoolingDeltaF)+f('pls-floor-heat','Floor heating ΔT (°F)',x.floorHeatingDeltaF)+f('pls-supply-dt','Supply-air ΔT for airflow (°F)',x.supplyAirDeltaF)+'</div><div class="pls-results" id="pls-results"></div><div id="pls-state" class="pls-state"></div><div id="pls-zones" class="pls-zones"></div><div class="pls-note">Method exposes conduction, outdoor-air, solar and internal-gain components with source IDs and constants. Equipment selection remains a later stage and does not overwrite this calculated load.</div>';
 var building=$('pbs-building');if(building&&building.parentNode)building.parentNode.insertBefore(s,building.nextSibling);else host.appendChild(s);s.addEventListener('input',onInput);s.addEventListener('change',onInput);document.addEventListener('input',schedule,true);document.addEventListener('change',schedule,true);calculate();return true}
function collect(){return {wallExposedAreaFt2:num('pls-wall-area'),roofAreaFt2:num('pls-roof-area'),outdoorIndoorGrainsDifference:num('pls-grains'),solarIrradianceBtuhFt2:num('pls-solar'),floorCoolingDeltaF:num('pls-floor-cool'),floorHeatingDeltaF:num('pls-floor-heat'),supplyAirDeltaF:num('pls-supply-dt')}}
function onInput(){write(LOAD,collect());calculate()}
var timer=null;function schedule(e){if(e&&e.target&&e.target.closest&&e.target.closest('#pls-load'))return;clearTimeout(timer);timer=setTimeout(calculate,20)}
function calculate(){if(!window.BrunoLoadEngine||!$('pls-results'))return;var b=read(BUILD,null),x=Object.assign(defaults(),read(LOAD,{})),r=window.BrunoLoadEngine.calculate(b||{},x);window.BrunoCurrentLoadResult=r;var res=$('pls-results'),state=$('pls-state'),zones=$('pls-zones');res.innerHTML='<div class="pls-card"><small>Cooling total</small><strong>'+fmt(r.cooling_total_Btuh)+' BTU/h</strong></div><div class="pls-card"><small>Sensible</small><strong>'+fmt(r.cooling_sensible_Btuh)+' BTU/h</strong></div><div class="pls-card"><small>Latent</small><strong>'+fmt(r.cooling_latent_Btuh)+' BTU/h</strong></div><div class="pls-card"><small>Heating</small><strong>'+fmt(r.heating_Btuh)+' BTU/h</strong></div><div class="pls-card"><small>Design airflow</small><strong>'+(r.design_supply_airflow_CFM==null?'—':fmt(r.design_supply_airflow_CFM)+' CFM')+'</strong></div>';
 if(r.input_completeness==='blocked'){state.className='pls-state bad';state.textContent='BLOCKED · missing: '+(r.missing||[]).join(', ')}else if(r.input_completeness==='provisional'){state.className='pls-state warn';state.textContent='PROVISIONAL · review: '+(r.provisional||[]).join(', ')}else{state.className='pls-state ok';state.textContent='COMPLETE INPUT SET · '+r.calculation_method}
 zones.innerHTML=(r.zone_loads||[]).length?'<strong>Zone allocation:</strong> '+r.zone_loads.map(function(z){return esc(z.name)+' '+fmt(z.cooling_total_Btuh)+' cool / '+fmt(z.heating_Btuh)+' heat BTU/h'}).join(' · '):'';}
function init(){var tries=0;(function wait(){if(ensure())return;if(++tries<100)setTimeout(wait,100)})()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
