'use strict';
const assert=require('assert');
const fs=require('fs');
const html=fs.readFileSync('ac-calculator.html','utf8');
const calc=fs.readFileSync('ac-calculator.js','utf8');
const bridge=fs.readFileSync('project-mode-bridge.js','utf8');
const wizard=fs.readFileSync('project-estimator-wizard.js','utf8');
const buildingUx=fs.readFileSync('project-building-ux.js','utf8');
const loadUx=fs.readFileSync('project-load-ux.js','utf8');
const equipmentUx=fs.readFileSync('project-equipment-ux.js','utf8');
const equipmentEngine=fs.readFileSync('project-equipment-engine.js','utf8');
const electricalUx=fs.readFileSync('project-electrical-ux.js','utf8');
const electricalEngine=fs.readFileSync('project-electrical-engine.js','utf8');
const navCss=fs.readFileSync('navigation-v2.css','utf8');
const css=fs.readFileSync('project-estimator-wizard.css','utf8');
const workspaceCss=fs.readFileSync('workspace-v5.css','utf8');
const sw=fs.readFileSync('sw.js','utf8');
const swRegister=fs.readFileSync('sw-register.js','utf8');

assert(html.includes('project-estimator-core.js'));
assert(html.includes('project-building-schema.js'));
assert(html.includes('project-load-engine.js'));
assert(html.includes('project-equipment-engine.js'));
assert(html.includes('project-estimator-wizard.js'));
assert(html.includes('project-building-ux.js'));
assert(html.includes('project-load-ux.js'));
assert(html.includes('project-equipment-ux.js'));
assert(html.includes('project-mode-bridge.js'));
assert(html.includes('secondary-drain-guard.js'));
assert(calc.includes("PROJECT_KEY='bruno-ac-project-plan-v1'"));
assert(calc.includes('appendProjectExtras(scope)'));
assert(calc.includes('projectBlockedReason()'));
assert(calc.includes("Commercial project is fail-closed"));
assert(bridge.includes("closest('#apply')"));
assert(bridge.includes("type()==='commercial'"));
assert(!bridge.includes('applyBtn.disabled=false'),'bridge must never force-enable Apply after Commercial mode');
assert(bridge.includes('enforceOneSurface'));
assert(bridge.includes("['sqft','systemType','indoorLocation','tonnage']"));
assert(bridge.includes("tons.dataset.legacyCapacity"));
assert(bridge.includes("open.hidden=true"));
assert(navCss.includes('.phase3-project-actions{display:none!important}'));
assert(wizard.includes('Materials & price preview'));
assert(buildingUx.includes('bruno-ac-building-envelope-v1'));
assert(buildingUx.includes('Building / Envelope / Load Inputs'));
assert(loadUx.includes('Heating / Cooling Load'));
assert(loadUx.includes('Transparent envelope/load model'));
assert(loadUx.includes('BLOCKED'));
assert(loadUx.includes('PROVISIONAL'));
assert(equipmentUx.includes('Equipment Capacity / Selection'));
assert(equipmentUx.includes('Verified max oversize fraction'));
assert(equipmentUx.includes('Operator override capacity BTU/h'));
assert(equipmentUx.includes('Override reason'));
assert(equipmentUx.includes("a.src='./project-electrical-engine.js'"),'equipment UI must chain the electrical dependency modules');
assert(equipmentUx.includes("b.src='./project-electrical-ux.js'"));
assert(equipmentEngine.includes('EQUIPMENT_SELECTION_MANUAL_S_01'));
assert(equipmentEngine.includes('EQUIPMENT_OEM_01'));
assert(equipmentEngine.includes('verified_equipment_selection_policy_required_for_upper_bound'));
assert(equipmentEngine.includes('catalog_or_OEM_equipment_dataset_required'));
assert(electricalUx.includes('Electrical Dependency'));
assert(electricalUx.includes('MCA/MOCP are never invented'));
assert(electricalUx.includes('Conductor verification source ID'));
assert(electricalEngine.includes('selected_OEM_equipment_required'));
assert(electricalEngine.includes('nameplate_MCA_required'));
assert(electricalEngine.includes('nameplate_MOCP_required'));
assert(electricalEngine.includes('selected_OCPD_exceeds_nameplate_MOCP'));
assert(electricalEngine.includes('Conductor size is not inferred from tonnage or MCA alone'));
assert(css.includes('.pew-price-strip'));
assert(workspaceCss.includes('.letterhead-strip select'));
assert(sw.includes("bruno-ac-v52"));
assert(sw.includes('freshAsset'));
assert(sw.includes("./project-building-schema.js"));
assert(sw.includes("./project-building-ux.js"));
assert(sw.includes("./project-load-engine.js"));
assert(sw.includes("./project-load-ux.js"));
assert(sw.includes("./project-equipment-engine.js"));
assert(sw.includes("./project-equipment-ux.js"));
assert(sw.includes("./project-electrical-engine.js"));
assert(sw.includes("./project-electrical-ux.js"));
assert(sw.includes("./code-library/hvac-calculation-source-matrix.json"));
assert(sw.includes("./secondary-drain-guard.js"));
assert(swRegister.includes("loadScript('service-journal-ux-js','./service-journal-ux.js')"));
console.log('project-estimator integration tests passed');
