'use strict';
const assert=require('assert');
const fs=require('fs');
const html=fs.readFileSync('ac-calculator.html','utf8');
const calc=fs.readFileSync('ac-calculator.js','utf8');
const bridge=fs.readFileSync('project-mode-bridge.js','utf8');
const wizard=fs.readFileSync('project-estimator-wizard.js','utf8');
const buildingUx=fs.readFileSync('project-building-ux.js','utf8');
const navCss=fs.readFileSync('navigation-v2.css','utf8');
const css=fs.readFileSync('project-estimator-wizard.css','utf8');
const workspaceCss=fs.readFileSync('workspace-v5.css','utf8');
const sw=fs.readFileSync('sw.js','utf8');
const swRegister=fs.readFileSync('sw-register.js','utf8');

assert(html.includes('project-estimator-core.js'));
assert(html.includes('project-building-schema.js'));
assert(html.includes('project-estimator-wizard.js'));
assert(html.includes('project-building-ux.js'));
assert(html.includes('project-mode-bridge.js'));
assert(html.includes('secondary-drain-guard.js'));
assert(calc.includes("PROJECT_KEY='bruno-ac-project-plan-v1'"));
assert(calc.includes('appendProjectExtras(scope)'));
assert(calc.includes('projectBlockedReason()'));
assert(calc.includes("Commercial project is fail-closed"));
assert(bridge.includes("closest('#apply')"));
assert(bridge.includes("type()==='commercial'"));
assert(!bridge.includes('applyBtn.disabled=false'),'bridge must never force-enable Apply after Commercial mode');
assert(bridge.includes('enforceOneSurface'));
assert(bridge.includes("['sqft','systemType','indoorLocation','tonnage']"),'duplicate legacy project inputs must be removed from visible authority');
assert(bridge.includes("tons.dataset.legacyCapacity"),'legacy capacity must be retained only as migration metadata');
assert(bridge.includes("open.hidden=true"),'legacy open-full action must not remain normal flow');
assert(navCss.includes('.phase3-project-actions{display:none!important}'),'outer project selector/standalone action must not be a second visible authority');
assert(wizard.includes('Materials & price preview'));
assert(wizard.includes('pew-price-strip'));
assert(wizard.includes("$('pew-sqft').oninput"));
assert(wizard.includes("textMoney('statCustomer')"));
assert(wizard.includes('Confirm & Save Calculation'));
assert(wizard.includes('bruno-ac-project-history-v1'));
assert(buildingUx.includes('bruno-ac-building-envelope-v1'));
assert(buildingUx.includes('Building / Envelope / Load Inputs'));
assert(buildingUx.includes('Design-condition source ID'));
assert(buildingUx.includes('Zone / room load details'));
assert(buildingUx.includes('Schema migration blocked'));
assert(css.includes('.pew-price-strip'));
assert(workspaceCss.includes('.letterhead-strip select'));
assert(sw.includes("bruno-ac-v49"));
assert(sw.includes('freshAsset'));
assert(sw.includes("./project-building-schema.js"));
assert(sw.includes("./project-building-ux.js"));
assert(sw.includes("./code-library/hvac-calculation-source-matrix.json"));
assert(sw.includes("./secondary-drain-guard.js"));
assert(swRegister.includes("loadScript('service-journal-ux-js','./service-journal-ux.js')"));
console.log('project-estimator integration tests passed');
