'use strict';
const assert=require('assert');
const fs=require('fs');
const {JSDOM}=require('jsdom');
const src=fs.readFileSync('project-mode-bridge.js','utf8');
const dom=new JSDOM('<!doctype html><html><head></head><body><main class="wrap"><div class="notice">Base notice</div><div id="projectEstimatorWizard"><div class="pew-sub"></div><div id="pew-finish-step"><div class="pew-step-title"><strong></strong><small></small></div></div></div><div class="grid"><div class="card"><h2>Legacy</h2></div></div></main><button id="apply">Apply</button><input id="tonnage" value="3 ton"><div id="jobbar"><span class="pill">3 ton / 36,000 BTU</span></div></body></html>',{url:'https://example.test/ac-calculator.html',runScripts:'outside-only'});
const w=dom.window;
w.localStorage.setItem('bruno-ac-project-context-v1',JSON.stringify({type:'commercial'}));
const apply=w.document.getElementById('apply');
apply.disabled=false;
w.eval(src);
assert.strictEqual(apply.disabled,false,'legacy bridge must not permanently disable commercial Apply; calculator/compliance gate owns readiness');
const banner=w.document.getElementById('bruno-commercial-mode');
assert(banner,'commercial informational banner must remain');
assert(/authoritative compliance gate/i.test(banner.textContent));
assert(w.document.documentElement.classList.contains('bruno-commercial-project'));
assert.strictEqual(w.document.getElementById('tonnage').value,'','legacy demo tonnage must still be ignored on the one-surface path');
assert(w.document.querySelector('#jobbar .pill').classList.contains('bruno-single-source-hidden'));
console.log('project-mode bridge runtime tests passed');
w.close();
