const assert=require('assert');
const fs=require('fs');
const path=require('path');
const R=require('../room-estimator-engine.js');
const Registry=require('../code-rule-registry.js');
const AC=require('../ac-calculator-engine.js');
const library=JSON.parse(fs.readFileSync(path.join(__dirname,'../code-library/texas-hvac-2026.json'),'utf8'));

(function presetPlanningBaseline(){const p=R.preset('typical-3-2');p.building.sqft=2000;const r=R.build(p);assert.strictEqual(r.metrics.supplyRegisters.calculatedBaseline,8);assert.strictEqual(r.metrics.supplyRegisters.codeMinimum,null);assert.ok(r.checks.some(x=>x.key==='equipment-sizing'));assert.ok(r.checks.some(x=>/not converted into tonnage/i.test(x.detail)));})();
(function roomTakeoffAndOverrides(){const p=R.preset('typical-3-2');p.building.ductScope='replace';p.building.returnGrillesDesign=2;p.rooms.forEach((x,i)=>{if(x.conditioned){x.branchFtPerRoom=10+i;x.areaEach=150+i*20;}});p.overrides.supplyRegisters={value:10,reason:'customer_request'};const r=R.build(p);assert.strictEqual(r.ready,true);assert.strictEqual(r.metrics.supplyRegisters.calculatedBaseline,8);assert.strictEqual(r.metrics.supplyRegisters.finalQuantity,10);assert.strictEqual(r.metrics.supplyRegisters.finalSource,'override');assert.strictEqual(r.metrics.returnGrilles.finalQuantity,2);assert.ok(r.metrics.ductFt.finalQuantity>0);const inputs=R.calculatorInputs(r);assert.strictEqual(inputs.supplyRegisters,10);assert.strictEqual(inputs.returnGrilles,2);})();
(function unresolvedDesignBlocks(){const p=R.preset('typical-3-2');p.building.ductScope='new';const r=R.build(p);assert.strictEqual(r.ready,false);assert.ok(r.blockers.some(x=>x.key==='ductFt'));assert.ok(r.blockers.some(x=>x.key==='returnGrilles'));})();
(function existingDuctDoesNotInventReturn(){const p=R.preset('typical-3-2');const r=R.build(p);assert.strictEqual(r.metrics.ductFt.finalQuantity,0);assert.strictEqual(r.metrics.returnGrilles.finalQuantity,null);})();
(function areaReconciliation(){const p=R.preset('typical-3-2');p.building.sqft=2000;p.rooms.forEach(x=>{if(x.conditioned)x.areaEach=50;});assert.ok(R.build(p).warnings.some(x=>/differs from building area by more than 15%/i.test(x)));})();
(function ruleTraceability(){assert.strictEqual(Registry.validateLibrary(library).ok,true);assert.strictEqual(Registry.validateCalculatorMap(library).ok,true);const r=R.build(R.preset('typical-3-2'));const entities=[];Object.values(r.metrics).forEach(x=>entities.push({key:x.key,ruleIds:x.ruleIds}));r.checks.forEach(x=>entities.push({key:x.key,ruleIds:x.ruleIds}));assert.deepStrictEqual(Registry.coverage(library,entities).missing,[]);})();
(function existingCalculatorReceivesRoomQuantities(){const p=R.preset('typical-3-2');p.building.ductScope='replace';p.building.returnGrillesDesign=2;p.rooms.forEach(x=>{if(x.conditioned)x.branchFtPerRoom=12;});p.overrides.supplyRegisters={value:9,reason:'contractor_choice'};const rr=R.build(p),generated=R.calculatorInputs(rr),scope=AC.buildScope(Object.assign({},AC.defaultInputs(),generated,{ductMode:'replace'}));assert.strictEqual(scope.requirements.find(x=>x.key==='supply-registers').qty,9);assert.strictEqual(scope.requirements.find(x=>x.key==='return-grilles').qty,2);})();
(function layeredEvaluation(){const a=R.preset('typical-3-2'),b=JSON.parse(JSON.stringify(a));assert.strictEqual(R.EVALUATION_LEVELS.length,8);assert.strictEqual(R.earliestDirtyLevel(a,b),null);b.overrides.supplyRegisters={value:12,reason:'customer_request'};assert.strictEqual(R.earliestDirtyLevel(a,b),4,'override-only change starts at L4');const c=JSON.parse(JSON.stringify(a));c.rooms[0].count=2;assert.strictEqual(R.earliestDirtyLevel(a,c),1,'room change starts at normalized model');const r=R.build(a);assert.ok(r.evaluation&&r.evaluation.levels.some(x=>x.level===6&&x.key==='pricing'));})();
console.log('room-estimator-engine tests: PASS');
